spring.application.name= desafioCriandoUmGeradorDeFrasesAleatorias
spring.datasource.url= jdbc:postgresql://localhost/desafio_frase_aleatoria
spring.datasource.username= ${POSTGRESQL_USERNAME}
spring.datasource.password= ${POSTGRESQL_PASSWORD}
spring.datasource.data-class-name= org.postgresql.Driver
spring.dialect= org.hibernate.dialectHSQLDialect
spring.jpa.hibernate.ddl-auto= update
